## Matrices

In [3]:
import numpy as np

In [4]:
arr = [[1,2], [3,4]]
print(arr)

[[1, 2], [3, 4]]


In [5]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
import torch

In [7]:
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

## Create matrices with default values

In [8]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [9]:
torch.ones((2,2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [10]:
np.random.rand(2,2)

array([[ 0.85550771,  0.13016092],
       [ 0.39524518,  0.71023192]])

In [11]:
torch.rand(2,2)


 0.5834  0.8846
 0.7369  0.8406
[torch.FloatTensor of size 2x2]

## Seeding (to keep random values same)

In [12]:
np.random.seed(0)

In [13]:
np.random.rand(2,2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [16]:
#seed
np.random.seed(0)
np.random.rand(2,2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [17]:
#torch seed
torch.manual_seed(0)
torch.rand(2,2)


 0.5488  0.5928
 0.7152  0.8443
[torch.FloatTensor of size 2x2]

In [19]:
torch.manual_seed(0)
torch.rand(2,2)
#same random array again!


 0.5488  0.5928
 0.7152  0.8443
[torch.FloatTensor of size 2x2]

In [21]:
#no seed
torch.rand(2,2)


 0.6028  0.8579
 0.5449  0.8473
[torch.FloatTensor of size 2x2]

In [23]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

## Numpy and Torch bridge

### Numpy to torch

In [24]:
np_array = np.ones((2,2 ))

In [25]:
print(np_array)

[[ 1.  1.]
 [ 1.  1.]]


In [26]:
print(type(np_array))

<class 'numpy.ndarray'>


In [32]:
#convert to tensor
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [36]:
#Data types
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

Numpy can convert some data types, but not all
Conversions are supported for:
1. double
2. float
3. int64, int32, unit8

In [37]:
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [39]:
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [40]:
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.ByteTensor of size 2x2]

In [42]:
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [43]:
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [44]:
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

### Torch to Numpy

In [45]:
torch_tensor = torch.ones(2, 2)

In [46]:
type(torch_tensor)

torch.FloatTensor

In [47]:
torch_to_numpy = torch_tensor.numpy()

In [48]:
type(torch_to_numpy)

numpy.ndarray

## Switching between GPU and CPU

In [50]:
#CPU
tensor_cpu = torch.ones(2, 2)

In [53]:
#CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [55]:
#GPU to CPU
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

## Tensor operations

### Resize tensor

In [57]:
a = torch.ones(2, 2)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [58]:
print(a.size())

torch.Size([2, 2])


In [59]:
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [60]:
a.view(4).size()

torch.Size([4])

### Element wise addition

In [65]:
a = torch.ones(2,2)
b = torch.ones(2,2)

print(a, b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]
 
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [73]:
# Element wise Addition

c = a + b
print("normal addition", c)

#OR

c = torch.add(a, b)
print("with torch.add", c)

normal addition 
 2  2
 2  2
[torch.FloatTensor of size 2x2]

with torch.add 
 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [74]:
# in-place addition
print("Old c tensor", c)

# _ does inplace addition
c.add_(a)

print("New c tensor", c)

Old c tensor 
 2  2
 2  2
[torch.FloatTensor of size 2x2]

New c tensor 
 3  3
 3  3
[torch.FloatTensor of size 2x2]



### Element wise-subtraction

In [79]:
a = torch.ones(2,2)
b = torch.ones(2,2)

print("original tensors", a, b)

print("Subtracted normally", a - b)

original tensors 
 1  1
 1  1
[torch.FloatTensor of size 2x2]
 
 1  1
 1  1
[torch.FloatTensor of size 2x2]

Subtracted normally 
 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [82]:
print(a.sub(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [83]:
#inplace
print(a.sub_(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]

